/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvatarMenu: typeof import('./src/components/avatarMenu.vue')['default']
    BundleMenu: typeof import('./src/components/bundleMenu.vue')['default']
    CameraMenu: typeof import('./src/components/cameraMenu.vue')['default']
    Menus: typeof import('./src/components/menus.vue')['default']
    Message: typeof import('./src/components/message.vue')['default']
    MessageBoard: typeof import('./src/components/messageBoard.vue')['default']
    Send: typeof import('./src/components/send.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanLoading: typeof import('vant/es')['Loading']
    VanOverlay: typeof import('vant/es')['Overlay']
  }
}
